services:
    nginx:
      container_name: nginx
      image: nginx:latest
      network_mode: host
      restart: always

    redis:
      container_name: redis
      image: redis:7.2-alpine
      ports: 
        - 6379:6379
      volumes:
        - redis_data:/data
      restart: always

volumes:
  redis_data: 
    
